library(tidyverse);theme_set(theme_bw())
library(shellpipes)

candat <- (rdsRead()
	|> mutate(report_type = ifelse(report_type == "cumIncidence","cumInc",report_type))
)
otherdat <- (csvRead()
	|> rowwise()
	|> mutate(report_value = ifelse(is.na(report_value),mean(c(report_lwr,report_upr)),report_value)
		, report_value = pmin(40000,report_value)
	)
	|> filter(source != "Imperial")
)

print(otherdat)
print(candat)

ggcumInc <- (ggplot(filter(candat,report_type == "cumInc",reporting == "low"),aes(date))
	+ geom_line(aes(y=med,color=effective_pop))
	+ geom_ribbon(aes(ymin=lwr,ymax=upr,fill=effective_pop),alpha=0.2)
	+ scale_color_manual(values=c("black","blue"))
	+ scale_fill_manual(values=c("black","blue"))
#	+ facet_wrap(~reporting,scale="free")
	+ xlim(as.Date(c("2026-05-01","2026-10-01")))
	+ geom_linerange(data=otherdat,aes(x=report_date,ymin=report_lwr,ymax=report_upr),color="red")
	+ coord_cartesian(xlim=c(as.Date("2026-05-01"),as.Date("2026-10-01"))
		,ylim=c(0,50000)
	)
	+ geom_text(data=otherdat,aes(x=report_date,y=report_value,label=source)
		, hjust=1.2, vjust=-0.8,size=3)
	+ theme(legend.position="bottom")
	+ labs(color='Proportion of population at risk',fill='Proportion of population at risk')
)

print(ggcumInc)
